
const Recipe = require('./models/Recipe');

const recipes = [
    {
        title: 'Spaghetti Bolognese',
        ingredients: [
        { name: 'Ground beef', quantity: '1 lb' },
        { name: 'Onion', quantity: '1, chopped' },
        { name: 'Garlic cloves', quantity: '2, minced' },
        { name: 'Tomato paste', quantity: '2 tbsp' },
        { name: 'Canned diced tomatoes', quantity: '1 can' },
        { name: 'Italian seasoning', quantity: '1 tsp' },
        { name: 'Salt', quantity: '1/2 tsp' },
        { name: 'Black pepper', quantity: '1/4 tsp' },
        { name: 'Spaghetti', quantity: '8 oz' },
        { name: 'Parmesan cheese', quantity: '1/4 cup, grated' },
        { name: 'Fresh basil leaves', quantity: 'for garnish' },
        ],
        steps: [
        'Heat oil in a large skillet over medium heat. Add the ground beef and cook until browned.',
        'Add the chopped onion and minced garlic. Cook until the onion is translucent.',
        'Stir in the tomato paste, diced tomatoes, Italian seasoning, salt, and black pepper.',
        'Simmer the sauce for 20 minutes, stirring occasionally.',
        'Meanwhile, cook the spaghetti according to package instructions.',
        'Serve the spaghetti topped with the Bolognese sauce. Garnish with grated Parmesan cheese and fresh basil leaves.',
        ],
        category: 'Main Course',
        tags: ['Pasta', 'Italian', 'Meat Sauce'],
        foodPicture: 'https://t4.ftcdn.net/jpg/02/40/99/19/240_F_240991913_c22j6WvLgpqiUvjaLiLc5rh14WO8jShB.jpg',
        ingredientsPhotoLink: 'https://example.com/spaghetti-bolognese-ingredients.jpg',
        createdBy: 'yonas',
    },

    {
        title: 'Chicken Stir-Fry',
        ingredients: [
        { name: 'Chicken breast', quantity: '2, boneless and skinless, sliced' },
        { name: 'Bell peppers', quantity: '2, sliced' },
        { name: 'Broccoli florets', quantity: '2 cups' },
        { name: 'Carrot', quantity: '1, julienned' },
        { name: 'Soy sauce', quantity: '2 tbsp' },
        { name: 'Hoisin sauce', quantity: '2 tbsp' },
        { name: 'Sesame oil', quantity: '1 tbsp' },
        { name: 'Garlic cloves', quantity: '2, minced' },
        { name: 'Ginger', quantity: '1-inch piece, grated' },
        { name: 'Cooking oil', quantity: '2 tbsp' },
        { name: 'Cooked rice', quantity: 'for serving' },
        { name: 'Green onions', quantity: 'for garnish' },
        ],
        steps: [
        'In a small bowl, whisk together the soy sauce, hoisin sauce, sesame oil, minced garlic, and grated ginger.',
        'Heat cooking oil in a large skillet or wok over high heat.',
        'Add the sliced chicken breast and cook until browned and cooked through.',
        'Remove the chicken from the skillet and set aside.',
        'In the same skillet, add the sliced bell peppers, broccoli florets, and julienned carrot. Stir-fry for a few minutes until crisp-tender.',
        'Return the cooked chicken to the skillet and pour the sauce mixture over the ingredients.',
        'Stir-fry for an additional 2-3 minutes until everything is well coated and heated through.',
        'Serve the chicken stir-fry over cooked rice. Garnish with sliced green onions.',
        ],
        category: 'Main Course',
        tags: ['Chicken', 'Stir-Fry', 'Asian'],
        foodPicture: 'https://www.kitchensanctuary.com/wp-content/uploads/2016/03/Quick-Chicken-Stir-Fry-tall-FS-42.webp',
        ingredientsPhotoLink: 'https://example.com/chicken-stir-fry-ingredients.jpg',
        createdBy: 'yonas',
    },

    {
        title: 'Taco Salad',
        ingredients: [
            { name: 'Ground beef', quantity: '1 lb' },
            { name: 'Taco seasoning', quantity: '2 tbsp' },
            { name: 'Lettuce', quantity: '4 cups, shredded' },
            { name: 'Tomatoes', quantity: '2, diced' },
            { name: 'Black beans', quantity: '1 can, drained and rinsed' },
            { name: 'Corn', quantity: '1 cup, canned or frozen' },
            { name: 'Cheddar cheese', quantity: '1 cup, shredded' },
            { name: 'Tortilla chips', quantity: '1 cup, crushed' },
            { name: 'Sour cream', quantity: '1/2 cup' },
            { name: 'Salsa', quantity: '1/2 cup' },
            { name: 'Avocado', quantity: '1, diced' },
        ],
        steps: [
            'In a skillet, cook the ground beef over medium heat until browned. Drain excess grease.',
            'Add the taco seasoning and cook according to package instructions.',
            'In a large bowl, combine the shredded lettuce, diced tomatoes, black beans, corn, cheddar cheese, and crushed tortilla chips.',
            'Add the cooked ground beef to the bowl and toss everything together.',
            'Serve the taco salad with a dollop of sour cream, salsa, and diced avocado on top.',
        ],
        category: 'Main Course',
        tags: ['Salad', 'Mexican', 'Taco'],
        foodPicture: 'https://st3.depositphotos.com/2075507/32876/i/1600/depositphotos_328768820-stock-photo-beef-taco-salad-bowl-dish.jpg',
        ingredientsPhotoLink: 'https://example.com/taco-salad-ingredients.jpg',
        createdBy: 'bimo',
    },

    {
    title: 'Chicken Parmesan',
    ingredients: [
        { name: 'Chicken breasts', quantity: '2, boneless and skinless' },
        { name: 'Eggs', quantity: '2, beaten' },
        { name: 'Bread crumbs', quantity: '1 cup' },
        { name: 'Parmesan cheese', quantity: '1/2 cup, grated' },
        { name: 'Marinara sauce', quantity: '2 cups' },
        { name: 'Mozzarella cheese', quantity: '1 cup, shredded' },
        { name: 'Spaghetti', quantity: '8 oz' },
        { name: 'Fresh basil leaves', quantity: 'for garnish' },
        { name: 'Salt', quantity: 'to taste' },
        { name: 'Black pepper', quantity: 'to taste' },
    ],
    steps: [
        'Preheat the oven to 375°F (190°C).',
        'Place the beaten eggs in a shallow dish and the bread crumbs mixed with grated Parmesan cheese in another shallow dish.',
        'Season the chicken breasts with salt and black pepper.',
        'Dip each chicken breast in the beaten eggs, then coat it with the bread crumb mixture.',
        'Heat oil in a skillet over medium heat. Cook the breaded chicken breasts until golden brown on both sides.',
        'Transfer the chicken breasts to a baking dish and pour marinara sauce over them. Top with shredded mozzarella cheese.',
        'Bake in the preheated oven for 20-25 minutes or until the chicken is cooked through and the cheese is melted and bubbly.',
        'While the chicken is baking, cook the spaghetti according to package instructions.',
        'Serve the baked chicken Parmesan over cooked spaghetti. Garnish with fresh basil leaves.',
    ],
    category: 'Main Course',
    tags: ['Chicken', 'Italian'],
    foodPicture: 'https://st.depositphotos.com/1692343/4976/i/600/depositphotos_49761737-stock-photo-homemade-italian-chicken-parmesan.jpg',
    ingredientsPhotoLink: 'https://example.com/chicken-parmesan-ingredients.jpg',
    createdBy: 'bimo',
    },

    {
    
        title: 'Classic Chocolate Chip Cookies',
        ingredients: [
            { name: 'All-purpose flour', quantity: '2 1/4 cups' },
            { name: 'Baking soda', quantity: '1/2 tsp' },
            { name: 'Salt', quantity: '1/2 tsp' },
            { name: 'Unsalted butter', quantity: '1 cup, softened' },
            { name: 'Granulated sugar', quantity: '3/4 cup' },
            { name: 'Brown sugar', quantity: '3/4 cup, packed' },
            { name: 'Vanilla extract', quantity: '1 tsp' },
            { name: 'Eggs', quantity: '2' },
            { name: 'Semi-sweet chocolate chips', quantity: '2 cups' },
        ],
        steps: [
            'Preheat the oven to 350°F (175°C) and line a baking sheet with parchment paper.',
            'In a medium bowl, whisk together the flour, baking soda, and salt.',
            'In a large bowl, cream together the softened butter, granulated sugar, and brown sugar until light and fluffy.',
            'Beat in the vanilla extract and eggs, one at a time, until well combined.',
            'Gradually add the dry ingredients to the wet ingredients, mixing until just combined.',
            'Stir in the chocolate chips.',
            'Drop rounded tablespoons of dough onto the prepared baking sheet, spacing them about 2 inches apart.',
            'Bake for 10-12 minutes or until the edges are golden brown.',
            'Allow the cookies to cool on the baking sheet for 5 minutes, then transfer them to a wire rack to cool completely.',
        ],
        category: 'Dessert',
        tags: ['Cookies', 'Chocolate', 'Baking'],
        foodPicture: 'https://st4.depositphotos.com/20661754/22570/i/600/depositphotos_225707720-stock-photo-classic-chocolate-chip-cookies.jpg',
        ingredientsPhotoLink: 'https://example.com/chocolate-chip-cookies-ingredients.jpg',
        createdBy: 'bimo',
    },
    
    {
    title: 'Grilled Chicken Caesar Salad',
    ingredients: [
        { name: 'Chicken breasts', quantity: '2, boneless and skinless' },
        { name: 'Romaine lettuce', quantity: '1 head, chopped' },
        { name: 'Croutons', quantity: '1 cup' },
        { name: 'Parmesan cheese', quantity: '1/2 cup, grated' },
        { name: 'Caesar dressing', quantity: '1/2 cup' },
        { name: 'Olive oil', quantity: '2 tbsp' },
        { name: 'Garlic cloves', quantity: '2, minced' },
        { name: 'Salt', quantity: 'to taste' },
        { name: 'Black pepper', quantity: 'to taste' },
    ],
    steps: [
        'Preheat the grill to medium-high heat.',
        'Season the chicken breasts with salt, black pepper, and minced garlic.',
        'Brush the chicken breasts with olive oil and place them on the preheated grill.',
        'Grill the chicken for 6-8 minutes per side or until cooked through.',
        'Remove the chicken from the grill and let it rest for a few minutes. Then, slice it into strips.',
        'In a large bowl, combine the chopped romaine lettuce, croutons, and grated Parmesan cheese.',
        'Add the sliced grilled chicken to the bowl and drizzle with Caesar dressing.',
        'Toss everything together until well coated.',
        'Serve the grilled chicken Caesar salad as a main course or side dish.',
    ],
    category: 'Main Course',
    tags: ['Salad', 'Grilled Chicken', 'Caesar'],
    foodPicture: 'https://media.istockphoto.com/id/534139231/photo/healthy-grilled-chicken-caesar-salad.webp?s=1024x1024&w=is&k=20&c=ibUzwSDRUg5gDIIQtODC6dKpGFDSE_JJhy8uBoBW_s0=',
    ingredientsPhotoLink: 'https://example.com/grilled-chicken-caesar-salad-ingredients.jpg',
    createdBy: 'bartoz',
    }

];

